apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: api
spec:
  replicas: 3
  workloadRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api
  strategy:
    canary:
      canaryService: canary-api-service
      stableService: api-service  
      trafficRouting:
        istio:
          virtualService: 
            name: api-vs
            routes:             
              - primary
#      analysis:
#        templates:
#        - templateName: success-rate
#        startingStep: 3 # delay starting analysis run until setWeight: 50%
#        args:
#        - name: service-name
#          value: canary-api-service.prod.svc.cluster.local
      steps:
      - setWeight: 50
      - pause:
          duration: 1m
      - analysis:
          args:
          - name: service-name
            value: canary-api-service.prod.svc.cluster.local
          templates:
          - templateName: success-rate
      - setWeight: 80
      - pause:
          duration: 10