apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: api
spec:
  replicas: 2
  workloadRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api
  strategy:
    canary:
      steps:
        - setWeight: 10
#        - pause: {}
        - pause:
            duration: 10
        - setWeight: 20
        - pause:
            duration: 10
        - setWeight: 60
        - pause:
            duration: 10
        - setWeight: 80
        - pause:
            duration: 40