apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

patchesStrategicMerge:
- mysql_env.yaml
- api_vs.yaml
- api_env.yaml
- api_replicas.yaml
- api_rollout.yaml
- istio-default-gw.yaml

configMapGenerator:
- literals:
  - MYSQL_USER=u_product
  - MYSQL_ROOT_HOST="%"
  - MYSQL_DATABASE="product"
  name: product-mysql-config

secretGenerator:
- literals:
  - MYSQL_PASSWORD="senha@prod"
  - MYSQL_ROOT_PASSWORD="root@prod"
  name: product-mysql-credentials
  type: Opaque
resources:
- ../../base
images:
- name: rogeriosilvarocha/api
  newName: rogeriosilvarocha/api
  newTag: 333eb20680a2f491fdf606cf4b65f21fb4ad5442
