apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

patchesStrategicMerge:
- mysql_env.yaml
- api_vs.yaml
- api_env.yaml
- api_replicas.yaml
- api_rollout.yaml
- istio-default-gw.yaml


configMapGenerator:
- literals:
  - MYSQL_USER=u_product
  - MYSQL_ROOT_HOST="%"
  - MYSQL_DATABASE="product"
  name: product-mysql-config

secretGenerator:
- literals:
  - MYSQL_PASSWORD="senha@prod"
  - MYSQL_ROOT_PASSWORD="root@prod"
  name: product-mysql-credentials
  type: Opaque
resources:
- ../../base
images:
- name: rogeriosilvarocha/api
  newName: rogeriosilvarocha/api
  newTag: 95ee1bc5f440fb0a10425ae03129380bc5f7f885
