apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  template:
    spec:
      containers:
      - name: mysql
        env:
        - name: env
          value: in-prod
        envFrom:
          - configMapRef:
              name: product-mysql-config
          - secretRef:
              name: product-mysql-credentials