apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api
  ports:
    - port: 8080
      targetPort: 8080   
#  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: canary-api-service
spec:
  selector:
    app: api
  ports:
    - port: 8080
      targetPort: 8080   
#  type: ClusterIP
