---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: api-vs
spec:
  gateways:
  - default-gw
  http:
  - name: primary 
    route:
    - destination:
        host: api-service
        port:
          number: 8080
    match:
    - uri:
        prefix: /api/
    rewrite:
      uri: /          
---