apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - mysql_deploy.yaml
  - mysql_svc.yaml
  - api_deploy.yaml
  - api_svc.yaml
  - api_vs.yaml
  - istio-default-gw.yaml
  
configurations:
  - https://argoproj.github.io/argo-rollouts/features/kustomize/rollout-transform.yaml  
