apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  template:
    spec:
      containers:
      - name: api
        env:
          - name: env
            value: in-dev
          - name: DB_PASS
            valueFrom:
              secretKeyRef: 
                name: product-mysql-credentials
                key: MYSQL_PASSWORD