apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dese

#nameSuffix: -dev

patchesStrategicMerge:
- mysql_env.yaml
- api_env.yaml

configMapGenerator:
- literals:
  - MYSQL_USER=u_product
  - MYSQL_ROOT_HOST="%"
  - MYSQL_DATABASE="product"
  name: product-mysql-config

secretGenerator:
- literals:
  - MYSQL_PASSWORD="senha@dese"
  - MYSQL_ROOT_PASSWORD="root@desee"
  name: product-mysql-credentials
  type: Opaque
resources:
- ../../base
images:
- name: rogeriosilvarocha/api
  newName: rogeriosilvarocha/api
  newTag: "0.1"
