name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: cd src && docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      
    - name: Create a file
      run: echo "I won't live long" > my_file.txt

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: my_file.txt
        retention-days: 5
