name: Docker build and push

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
on: workflow_dispatch

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
#    - name: Build the Docker image
#      run: cd src && docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      
    - name: Create a file
      run: echo "I won't live long" > my_file.txt

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: my_file.txt
        retention-days: 5
    
    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}      
#    - name: Extract metadata (tags, labels) for Docker
#      id: meta
#      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
#      with:
#        images: bdmg/my-docker-hub-repository         
    - name: Build and push Docker image
      uses: docker/build-push-action@v3     
      with:
        context: ./src
        push: true
        tags: |
          bdmg/api-product:latest
          bdmg/api-product:v2
#        tags: ${{ steps.meta.outputs.tags }}
#        labels: ${{ steps.meta.outputs.labels }}
