name: Test composite action
on: 
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v3
      - id: foo
        uses: rogeriorocha/hello-world-composite-action@master
        with:
          entrypoint: /test   
          dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
